site_name: Portfolio - Rami Alshuhayed
site_url: https://he11223ro-svg.github.io/
site_author: Rami Alshuhayed

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.expand
    - navigation.top

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
    - Лабораторная 1 (Python Basics): labs/lab1.md
    - Лабораторная 2 (NumPy & Data): labs/lab2.md
    - Лабораторная 3 (CI/CD): labs/lab3.md
    - Лабораторная 4 (Classification): labs/lab4.md
    - Лабораторная 5 (Regression): labs/lab5.md
    - Лабораторная 6 (Extract-Transform): labs/lab6.md
    - Лабораторная 7 (Анализ текста): labs/lab7.md
    - Лабораторная 8 (Скрапинг): labs/lab8.md